# Generated by Django 5.0.1 on 2024-02-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydata',
            name='file_name',
            field=models.CharField(default='test', max_length=50),
            preserve_default=False,
        ),
    ]
