# Generated by Django 5.0.1 on 2024-02-22 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo_docs', '0003_image_pdfdocuments_delete_mydata'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PdfDocuments',
            new_name='Document',
        ),
    ]
