# Generated by Django 5.0.1 on 2024-02-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_docs', '0004_rename_pdfdocuments_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(unique=True)),
            ],
        ),
    ]
