# Generated by Django 5.0.1 on 2024-02-29 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_docs', '0006_alter_blog_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
