# Generated by Django 5.0.1 on 2024-03-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_docs', '0008_document_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_goed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
