# Generated by Django 4.2.6 on 2023-10-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kleur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Soort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Dier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=20)),
                ('grootte', models.IntegerField()),
                ('kleur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dieren.kleur')),
                ('soort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dieren.soort')),
            ],
        ),
    ]
