# Generated by Django 4.2.7 on 2023-11-28 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0002_immowebdata_original_id_immowebdata_postal_code_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='immowebdata',
            name='unique_id',
        ),
        migrations.RemoveField(
            model_name='immowebdata',
            name='original_id',
        ),
        migrations.RemoveField(
            model_name='immowebdata',
            name='postal_code',
        ),
    ]
