# Generated by Django 4.2.7 on 2023-12-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapers', '0004_immowebdata_original_id_immowebdata_postal_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='immowebdata',
            name='price',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
