# Generated by Django 4.2.5 on 2023-09-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text_2',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
