# Generated by Django 4.2.5 on 2023-09-14 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_question_text_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text_2',
        ),
    ]
